feat: use rabbit
projector-course/history-service pull request #5
Opened 2021-12-21 19:14 UTC by mykhailo-vaskivnyuk

2021-12-24 21:40 UTC, welikoiwanenko commented on src/services/amqp.js
> +    callback(m.content).then(() => channel.ack(m));
await

2022-01-05 16:10 UTC, welikoiwanenko requested changes
https://github.com/projector-course/video-service/pull/6#pullrequestreview-844784471

2022-01-05 16:56 UTC, mykhailo-vaskivnyuk commented on src/services/amqp.js
> +    callback(m.content).then(() => channel.ack(m));
ок

2022-01-05 20:03 UTC, welikoiwanenko requested changes

2022-01-05 20:03 UTC, welikoiwanenko commented on src/services/amqp.js
> +    await callback(m.content).then(() => channel.ack(m));
Так, давай определимся:)
.then используем, если мы вызываем асинхронную функцию без await, и хотим после неё что-то выполнить.
твой колбэк асинхронен? Тогда:
```
await callback(m.content)
await channel.ack(m);
```

2022-01-06 18:01 UTC, mykhailo-vaskivnyuk commented on src/services/amqp.js
> +    await callback(m.content).then(() => channel.ack(m));
ок

2022-01-07 13:13 UTC, welikoiwanenko approved these changes

2022-01-07 13:57 UTC, merged